apiVersion: v1
kind: Namespace
metadata:
  name: fast-track-istio 
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookclub
  namespace: fast-track-istio 
  labels:
    app: bookclub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookclub
  template:
    metadata:
      labels:
        app: bookclub
    spec:
      containers:
        - name: bookclub
          image: fasttrackistio/bookclub:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: moviesServiceUri
              value: "http://movies-api-service.fast-track-istio.svc.cluster.local:3000"
            - name: booksServiceUri
              value: "http://books-api-service.fast-track-istio.svc.cluster.local:4000"
            - name: independentServiceUri
              value: "http://independent.australiaeast.azurecontainer.io:8080/"
          resources:
            limits:
              cpu: "200m"
              memory: 200Mi
            requests:
              cpu: "100m"
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bookclub
  namespace: fast-track-istio
  labels:
    app: bookclub
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: bookclub
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: book-club-gateway
  namespace: fast-track-istio
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-book-club-gateway
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: book-club-vservice
  namespace: fast-track-istio
spec:
  hosts:
    - "*"
  gateways:
    - book-club-gateway
  http:
    - route:
        - destination:
            host: bookclub
            port:
              number: 8080
