apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bookclub-gw-vs-svc-deploy.yaml
  - books-api-svc-deploy.yaml
  - legacy-api-svc-deploy.yaml
  - movies-api-svc-deploy.yaml