apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy
  labels:
    app: legacy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: legacy
  template:
    metadata:
      labels:
        app: legacy
    spec:
      containers:
        - name: legacy
          image: fasttrackistio/legacy-books:1.0.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: legacy
  labels:
    app: legacy
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: legacy