apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookclub
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: bookclub
          image: fasttrackistio/bookclub:1.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bookclub
  labels:
    run: bookclub
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: bookclub