apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesv2
  labels:
    app: moviesv2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moviesv2
  template:
    metadata:
      labels:
        app: moviesv2
    spec:
      containers:
        - name: moviesv2
          image: fasttrackistio/movies:2.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: movies
  labels:
    app: movies
spec:
  ports:
  - port: 6000
    protocol: TCP
  selector:
    app: movies