apiVersion: v1
kind: Namespace
metadata:
  name: fast-track-istio 
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  namespace: fast-track-istio 
  labels:
    app: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: fasttrackistio/books:1.0.0
          ports:
            - name: http-books-api
              containerPort: 80
          resources:
            limits:
              cpu: "200m"
              memory: 200Mi
            requests:
              cpu: "100m"
              memory: 100Mi
          env:
            - name: LegacyServiceUri
              value: "http://legacy-api-service.fast-track-istio.svc.cluster.local:7000"
---
apiVersion: v1
kind: Service
metadata:
  name: books-api-service
  namespace: fast-track-istio 
  labels:
    app: books
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: http-books-api
  selector:
    app: books
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: books-api-vservice
  namespace: fast-track-istio
spec:
  hosts:
    - books.fast-track-istio.io
  gateways:
    - books-api-gateway
  http:
    - route:
        - destination:
            host: books-api-service
            port:
              number: 4000