apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-club
  labels:
    app: book-club
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: book-club
          image: fasttrackistio/bookclub:1.0.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: book-club
  labels:
    app: book-club
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: book-club
