apiVersion: apps/v1
kind: Deployment
metadata:
  name: independent
  labels:
    app: independent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: independent
  template:
    metadata:
      labels:
        app: independent
    spec:
      containers:
        - name: independent
          image: fasttrackistio/independent:1.0.0
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: independent
  labels:
    app: independent
spec:
  ports:
  - port: 7000
    protocol: TCP
  selector:
    app: independent