apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: movies-api-authn-policy
  namespace: fast-track-istio
spec:
  targets:
    - name: movies-api-service
  origins:
    - jwt:
        issuer: "fast-track-istio.io"
        jwksUri: "https://raw.githubusercontent.com/Istio-Succinctly/Policies/master/Static/jwks.json"
  principalBinding: USE_ORIGIN